/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutumnRouteImport } from './routes/autumn'
import { Route as HalloweenRouteImport } from './routes/halloween'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as SpecialsRouteImport } from './routes/specials'
import { Route as ThanksgivingRouteImport } from './routes/thanksgiving'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutumnRoute = AutumnRouteImport.update({
  id: '/autumn',
  path: '/autumn',
  getParentRoute: () => rootRouteImport,
} as any)
const HalloweenRoute = HalloweenRouteImport.update({
  id: '/halloween',
  path: '/halloween',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialsRoute = SpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksgivingRoute = ThanksgivingRouteImport.update({
  id: '/thanksgiving',
  path: '/thanksgiving',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autumn': typeof AutumnRoute
  '/halloween': typeof HalloweenRoute
  '/oracle': typeof OracleRoute
  '/specials': typeof SpecialsRoute
  '/thanksgiving': typeof ThanksgivingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autumn': typeof AutumnRoute
  '/halloween': typeof HalloweenRoute
  '/oracle': typeof OracleRoute
  '/specials': typeof SpecialsRoute
  '/thanksgiving': typeof ThanksgivingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autumn': typeof AutumnRoute
  '/halloween': typeof HalloweenRoute
  '/oracle': typeof OracleRoute
  '/specials': typeof SpecialsRoute
  '/thanksgiving': typeof ThanksgivingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/autumn' | '/halloween' | '/oracle' | '/specials' | '/thanksgiving'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autumn' | '/halloween' | '/oracle' | '/specials' | '/thanksgiving'
  id:
    | '__root__'
    | '/'
    | '/autumn'
    | '/halloween'
    | '/oracle'
    | '/specials'
    | '/thanksgiving'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutumnRoute: typeof AutumnRoute
  HalloweenRoute: typeof HalloweenRoute
  OracleRoute: typeof OracleRoute
  SpecialsRoute: typeof SpecialsRoute
  ThanksgivingRoute: typeof ThanksgivingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autumn': {
      id: '/autumn'
      path: '/autumn'
      fullPath: '/autumn'
      preLoaderRoute: typeof AutumnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halloween': {
      id: '/halloween'
      path: '/halloween'
      fullPath: '/halloween'
      preLoaderRoute: typeof HalloweenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specials': {
      id: '/specials'
      path: '/specials'
      fullPath: '/specials'
      preLoaderRoute: typeof SpecialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanksgiving': {
      id: '/thanksgiving'
      path: '/thanksgiving'
      fullPath: '/thanksgiving'
      preLoaderRoute: typeof ThanksgivingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutumnRoute: AutumnRoute,
  HalloweenRoute: HalloweenRoute,
  OracleRoute: OracleRoute,
  SpecialsRoute: SpecialsRoute,
  ThanksgivingRoute: ThanksgivingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
